var quotes = [
  'Be who you are and say what you feel, because those who mind don\'t matter and those who matter don\'t mind.',
  'This too, shall pass.',
  'Keep your eyes on the stars and your feet on the ground.',
  'The only person you should try to be better than is the person you were yesterday.',
  'Never be bullied into silence. Never allow yourself to be made a victim. Accept no one\'s definition of your life; define yourself.',
  'Faith is the art of holding on to things your reason has once accepted, in spite of your changing moods.',
  'A man who flies from his fear may find that he has only taken a shortcut to meet it.',
  'Life\'s too mysterious to take too serious.',
  'No one can make you feel inferior without your consent.',
  'The woman who follows the crowd will usually go no further than the crowd. The woman who walks alone is likely to find herself in places no one has been before.',
  'You can\'t go around building a better world for people. Only people can build a better world for people. Otherwise it\'s just a cage.',
  'There isn\'t a way things should be. There\'s just what happens, and what we do.',
  'It\'s not about how hard you can hit; it\'s about how hard you can get hit and keep moving forward.',
  'If you want to go fast, go alone. If you want to go far, go together.',
  'It\'s OK to not be OK, as long as you don\'t stay that way.',
  'I can be changed by what happens to me but I refuse to be reduced by it.',
  'Believe you can and you\'re halfway there.',
  'May I never be complete. May I never be content. May I never be perfect.',
  'Nothing in life is to be feared; it is only to be understood. Now is the time to understand more so that we may fear less.',
  'Those who don\'t believe in magic will never find it.',
  'There is no elevator to success, you have to take the stairs.',
  'Plant your garden and decorate your own soul, instead of waiting for someone to bring you flowers.',
  'It does not do to dwell on dreams and forget to live.',
  'Don\'t sweat the petty things and don\'t pet the sweaty things.',
  'Do what you feel in your heart to be right, for you\'ll be criticized anyway.',
  'Do not set yourself on fire in order to keep others warm.',
  'The way I see it, every life is a pile of good things and bad things. The good things don\'t always soften the bad things, but vice versa, the bad things don\'t always spoil the good things and make them unimportant.',
  'It\'s supposed to be hard. If it were easy, everyone would do it.',
  'Ask yourself if what you\'re doing today will get you closer to where you want to be tomorrow.',
  'Life may not be the party we hoped for, but while we\'re here, we should dance.',
  'Never cowardly or cruel. Never give up, never give in.',
  'Do not go where the path may lead, go instead where there is no path and leave a trail.',
  'In 20 years, you probably won\'t even remember this.',
  'Love all, trust a few, do wrong to none.',
  'Clear eyes, full hearts, can\'t lose.',
  'We are what we repeatedly do. Excellence, then, is not an act, but a habit.',
  'Life has many ways of testing a person\'s will, either by having nothing happen at all or by having everything happen all at once.',
  'There are two ways of spreading light: to be the candle, or the mirror that reflects it.',
  'Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.',
  'Hate. It has caused a lot of problems in this world but has not solved one yet.',
  'If opportunity doesn\'t knock, build a door.',
  'An attitude of positive expectation is the mark of the superior personality.',
  'Success consists of going from failure to failure without loss of enthusiasm.',
  'If you can dream it, then you can achieve it. You will get all you want in life if you help enough other people get what they want.',
  'The only place where your dream becomes impossible is in your own thinking.',
  'We don\'t see things as they are, we see them as we are.',
  'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.',
  'I may not have gone where I intended to go, but I think I have ended up where I needed to be.',
  'Learning is a gift. Even when pain is your teacher.',
  'I\'ve had a lot of worries in my life, most of which never happened.',
  'You yourself, as much as anybody in the entire universe, deserve your love and affection.',
  'Hope is a waking dream.',
  'The past has no power over the present moment.',
  'Happiness is an attitude. We either make ourselves miserable, or happy and strong. The amount of work is the same.',
  'I do believe we\'re all connected. I do believe in positive energy. I do believe in the power of prayer. I do believe in putting good out into the world. And I believe in taking care of each other.',
  'If you want light to come into your life, you need to stand where it is shining.',
  'Today is a new beginning, a chance to turn your failures into achievements & your sorrows into so goods. No room for excuses.',
  'Life is a gift, and it offers us the privilege, opportunity, and responsibility to give something back by becoming more.',
  'We are all here for some special reason. Stop being a prisoner of your past. Become the architect of your future.',
  'If you think you can do a thing or think you can\'t do a thing, you\'re right.',
  'No matter what the situation, remind yourself you have a choice.',
  'All you can change is yourself, but sometimes that changes everything.',
  'The will to win, the desire to succeed, the urge to reach your full potential… these are the keys that will unlock the door to personal excellence.',
  'If we\'re growing, we\'re always going to be out of our comfort zone.',
  'Take chances, make mistakes. That\'s how you grow. Pain nourishes your courage. You have to fail in order to practice being brave.',
  'I am the greatest, I said that even before I knew I was.',
  'We are responsible for what we are, and whatever we wish ourselves to be, we have the power to make ourselves.',
  'The difference between stumbling blocks and stepping stones is how you use them.',
  'If someone tells you, "you can\'t" they really mean, "I can\'t".',
  'There is little difference in people, but that little difference makes a big difference. The little difference is attitude. The big difference is whether it is positive or negative.',
  'Whatever you want to do, do it now. There are only so many tomorrows.',
  'When I do good, I feel good. When I do bad, I feel bad. That\'s my religion.',
  'The difference in winning and losing is most often… not quitting.',
  'You are never too old to set another goal or dream a new dream.',
  'All things are difficult before they are easy.',
  'Success is falling nine times and getting up ten.',
  'Happiness, like unhappiness, is a proactive choice.',
  'The next time you feel slightly uncomfortable with the pressure in your life, remember no pressure, no diamonds. Pressure is a part of success.',
  'When the world pushes you to your knees, you\'re in the perfect position to pray.',
  'If you can change your mind, you can change your life.',
  'When we are no longer able to change a situation, we are challenged to change ourselves.',
  'Happiness often sneaks in through a door you didn\'t know you left open.',
  'The best way to gain self-confidence is to do what you are afraid to do.'
]

function newQuote() {
  var ranNum = Math.floor(Math.random() * (quotes.length));
  document.getElementById('quote-display').innerHTML = '"' + quotes[ranNum] + '"';
}
